project:
  type: website

website:
  title: "Creating Conflict"
  navbar:
    left:
      - href: conflict-presentation.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true


